### PR TITLE
Disable entirely rspamd

### PR DESCRIPTION
**Pull request by stephdl**
https://github.com/NethServer/dev/issues/6131

To stop rspamd spam checking, It is not enough to disable the modules, we have many, many symbols still enabled

### CODE REVIEW

**Comment by stephdl** [comment]
with this patch I aime to have this for all smtp transaction if SpamCheckStatus eq 'disabled' 

`(default: F (no action): [0.00/19.90] [])`


why Travis has not pushed the rpm in this PR @DavidePrincipi

**Comment by gsanchietti** [comment]
IMHO this is not the correct way to implement such thing.
If `SpamCheckStatus` and `VirusCheckStatus` are disabled, also the `status` prop should be disabled.

**Comment by DavidePrincipi** [comment]
> To stop rspamd spam checking, It is not enough to disable the modules, we have many, many symbols still enabled

Can we make them uneffective by adding a positive score? e.g. +1000

**Comment by stephdl** [comment]
> IMHO this is not the correct way to implement such thing.
If SpamCheckStatus and VirusCheckStatus are disabled, also the status prop should be disabled.

you have forgotten that we can reject also with rspamd file type, does it is archive, executable, doc...

So we need the multimap enabled even if spam or virus are disabled

> Can we make them uneffective by adding a positive score? e.g. +1000
So instead of stop to analyse spam, add a score 1000, we will continue to analyse spam in logs, set score to email, reject gtube spam test. This will lead to question for the sysadmin....why I still continue to add score. possible way but not really nice IMHO

> I understand the issue, but the proposed solution looks complex to maintain.

RSPAMd is complex, sometimes messy, however we need to make it workable. We could only stop the lua rule `SPOOF_REPLYTO` that has a score of `6` maybe other rules from `headers` that have also some positive score and in 6 month comes with another lua rule implemented that will add new positive score to our spam virus.

we could also have a static list of disabled rule/symbol  instead of dynamic (eg display the dynamic template as a static list) and use it, with the possibility that we have to add/remove/modify some rules/symbols in some time.

**Comment by DavidePrincipi** [comment]
I think we are still trying to implement a behavior that came out of the box with amavisd. Rspamd has nothing to do with it. Instead of pushing it further it's maybe better to change our expectations. If necessary change the UI to avoid communicating false expectations.

**Comment by stephdl** [comment]
if we turn off rspamd, postfix cannot connect to rspamd socket and will soft reject email, this is a new behaviour we are creating

**Comment by DavidePrincipi** [comment]
Could you attach a screenshot of the resulting Coeckpit UI?

**Comment by stephdl** [comment]
With this new scenario, now someone who has `SpamCheckStatus` disabled before the upgrade, then we stop entirely the filters, no more antivirus, no more attachment filter

**Comment by stephdl** [comment]
Screenshot (51)
Screenshot (50)

**Comment by stephdl** [comment]
can I merge and write the QA @DavidePrincipi ?

**Comment by DavidePrincipi** [comment]
An alternative solution could be a migrate fragment that removes `SpamCheckStatus` and maps it to `status` what do you think?

**Comment by gsanchietti** [comment]
I like Davide idea, but I need to gather feedback from the support team. Please, hold on! ;)

**Comment by stephdl** [comment]
not sure to understand @DavidePrincipi but no need of migrate fragment to reflect the status of `SpamCheckStatus` to status, I use the value of `SpamCheckStatus` to enabled/disabled status. The idea behind is to low the changes in the UI

**Comment by stephdl** [comment]
obsoleted by https://github.com/NethServer/nethserver-mail/pull/196

**Pull request closed without merging**
