### PR TITLE
ui. fix imapsync typo errors

### PR DESCRIPTION
**Pull request by federicoballarini**
Fixed ImapSync typo errors.

NethServer/dev#6376

### CODE REVIEW

**Review by stephdl — APPROVED** [review]
it is ok for me, good shot, please could you open an issue to make a QA, I will merge it after

Thank

**Comment by gsanchietti** [comment]
This is cosmetic but could cause regressions.
I agree for a new issue or at least we can merge into a single issue with #237

**Comment by federicoballarini** [comment]
Tell me if you prefer a new issue or we can use the existing one

**Comment by gsanchietti** [comment]
Let's bind it to issue 6376

**Pull request merged**
