### PR TITLE
Move 20smarthost_recipient fragment to smarthost package

### PR DESCRIPTION
**Pull request by gsanchietti**
If the common package is not installed, the smarthost package
will fail the expansion of the transport template with following errors:
```
  [WARNING] expansion of /etc/postfix/transport failed
  Action: /etc/e-smith/events/actions/generic_template_expand FAILED: 1
  Event: nethserver-mail-smarthost-update FAILED
```

NethServer/dev#6180

### CODE REVIEW

**Comment by gsanchietti** [comment]
> I don't understand.
> 
> If the common package is not installed how the template fragment can issue the warning message?

The error (not warning) is raised from the smarthost package which tries to expand a template present only inside the common package (which is not installed from the smarhost package).
So the template must be present in all 3 packages: smarthost, common and server.

**Comment by DavidePrincipi** [comment]
>  So the template must be present in all 3 packages: smarthost, common and server.

Are we sure it is necessary to expand it in smarthost?

https://github.com/NethServer/nethserver-mail/commit/f390330c192323436ee20d115268b50747f57bc8

The smarthost package was (is?) designed to be always installed, to configure just the default smarthost and thus to be very basic. Additional smarthost settings, which depend on the recipient or the sender or whatever are likely to be bundled within the mail-server package.

**Comment by gsanchietti** [comment]
> Are we sure it is necessary to expand it in smarthost?

I'm pretty sure, the called event is (nethserver-mail-smarthost-save)[https://github.com/NethServer/nethserver-mail/blob/master/api/send/update#L60].

A different solution would be refactor the API to call another event, but which one?
IMO this is the simplest, but I'm open to other solutions.

**Comment by gsanchietti** [comment]
As a side note, I have to say that we need to release this fix *very soon*. Because all 7.8 installations on a CentOS are failing.

**Comment by DavidePrincipi** [comment]
I think the commit https://github.com/NethServer/nethserver-mail/commit/f390330c192323436ee20d115268b50747f57bc8 introduced the regression and needs to be fixed.

In general, wherever it adds things to smarthost, move them elsewhere (to mail-common?)

So your move here of 20smarthost_recipient actually is not needed. Instead move

- Fragment https://github.com/NethServer/nethserver-mail/commit/f390330c192323436ee20d115268b50747f57bc8#diff-37d424d378acefea61da9a0916ebeacb
- Possibly fragment https://github.com/NethServer/nethserver-mail/commit/f390330c192323436ee20d115268b50747f57bc8#diff-7b4bd724c00076844a50e7a72d046436
- Line https://github.com/NethServer/nethserver-mail/commit
/f390330c192323436ee20d115268b50747f57bc8#diff-0526e222769c16cc189a5c8739077d30R34

**Comment by gsanchietti** [comment]
Moving the fragment to `mail-common` is not enough because `mail-smarthost` needs to expand the `transport` template inside the `nethserver-mail-smarthost-save` event.

**Pull request merged**
